namespace Compiler.Syntax;
public enum SyntaxKind {
    // Tokens
    InvalidToken,
    EndOfFileToken,
    WhitespaceToken,
    NumberToken,
    CloseParenthesisToken,
    OpenParenthesisToken,
    PlusToken,
    MinusToken,
    StarToken,
    SlashToken,
    StarStarToken,
    SlashSlashToken,
    SlashStarToken,
    EqualsToken,
    //PlusEqualsToken,
    //MinusEqualsToken,
    //StarEqualsToken,
    //SlashEqualsToken,
    LessthanToken,
    MorethanToken,
    EqualsEqualsToken,
    LessthanEqualsToken,
    MorethanEqualsToken,
    EndOfExpressionToken,
    VariableToken,

    // Expressions
    AssignmentExpression,
    BinaryExpression,
    BooleanExpression,
    UnaryExpression,
    ParenthesizedExpression,
    LiteralExpression,
    VariableExpression,
}
